project:
  type: book

license: "CC BY-SA"


latex-auto-install: true

crossref:
  fig-prefix: figure     # (default is "Figure")
  tbl-prefix: tableau    # (default is "Table")

# setting fr-FR causes the date to be in english?
lang: fr
# language: _language.yml   # customized, "tableau" plutôt que "table", etc.

book:

  title: "Analyse et conception de logiciels"
  cover-image: images/wordle_ordre_alph.png
  image: images/wordle_ordre_alph.png
  
  author: 
    - "Christopher Fuhrman"
    - "Yvan Ross"
  date: last-modified
  date-format: "DD MMMM YYYY à HH:mm:ss Z"

  chapters:
    - index.qmd # Preface
    - AnalyseConception.qmd
    - Besoins.qmd
    - CasUtilisation.qmd
    - MDD.qmd
    - DSS.qmd
    - GRASP.qmd
    - DetteTechnique.qmd
    - Contrats.qmd
    - RDCU.qmd
    - TDD.qmd
    - Réusinage.qmd
    - TravailEquipe.qmd
    - Outils-UML.qmd
    - GRASP-GoF.qmd
    - Fiabilité.qmd
    - Diagrammes d'activités.qmd
    - Diagrammes d'états.qmd
    - ConceptionPackages.qmd
    - Diagrammes de déploiement.qmd
    - Laboratoires.qmd
    - references.qmd
    # Annexes
  appendices:
    - Exercice_Classes_conceptuelles_dans_le_MDD.qmd
    - Exercice_Diagramme_de_classes_conceptuelles_MDD.qmd
    - Exercice_Contrats_d_opération.qmd
    - Exercice_DSS_Diagrammes-de-séquence-système.qmd
    - Exercice_Diagramme_états.qmd
    - Exercice-diagramme_d_activité.qmd
    - Exercice_Identifier_GRASP_dans_GoF.qmd
    - Exercice_Critique_d-une_conception.qmd
    - Exercice-Coder_des_méthodes_des_DS.qmd
    - Exercice_Adaptateur_pour_Maps_CF.qmd
  # repo-actions: [source, issue]

bibliography: references.bib
citations-hover: true
citation-location: document
link-citations: true # pandoc setting
# citeproc: true # causes quarto to hang
# latex-auto-install: true
latex-auto-mk: true
link-external-icon: true

appendix-style: default

format:

  # epub: 
  #   epub-cover-image: "images/wordle_ordre_alph.png"

  html:
    title-block-banner: true
    header-includes: |
      <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
            rel="stylesheet" data-external="1"/>
      <style type="text/css">
        @font-face {
          font-family: 'xkcd Script';
          src: url('web-resources/xkcd-font/xkcd-script.ttf') format('truetype');
        }
      </style>
    # https://quarto.org/docs/output-formats/html-themes.html#overview
    resources: web-resources/**
    theme: simplex
    

  pdf:
    # has to be latexmk for .plantuml plugin to work (because it generates .svg files)
    pdf-engine: latexmk
    # thanks: "Thanks here"
    template: partials/template.tex
    # babel-lang: french
    colorlinks: true
    documentclass: scrbook
    toc: true
    toc-depth: 2
    lof: true
    lot: true
    highlight-style: github
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    fontfamily: libertinus
    fontfamilyoptions: 
      - osf
      - p
    fontsize: 11pt
    header-includes: 
      - \usepackage{colortbl}
      - \usepackage[scaled=.8]{cascadia-code}
    # Bibliographies in French have raised r and e for the number "édition" e.g. 1re, 3e
      - \DeclareUnicodeCharacter{1D49}{$^\text{e}$}
      - \DeclareUnicodeCharacter{02B3}{$^\text{r}$}
      - \usepackage{titling}
      - \usepackage{transparent}
      - \pretitle{\begin{center}
        \transparent{0.4}\includegraphics[]{images/wordle_ordre_alph.png}\transparent{1.0}\huge\\}
      - \posttitle{\end{center}}

# filters must be run in the proper order here
filters:
  - filters/fr-nbsp.lua
  - filters/diagram-generator.lua
  - quarto
  - filters/inline-svg.lua
  - filters/pandoc-quotes.lua

#
# Note: If JAVA_HOME, PLANTUML and DOT system variables are correctly set 
# (and the tools they point to are installed), 
# you should not need the following meta data variables
#

# javaPath: C:/Program Files/Java/jdk1.8.0_331/bin/java.exe
# plantumlPath: G:/My Drive/PlantUML/plantuml.jar
# dotPath: C:/Program Files/Graphviz/bin/dot.exe

### citation info
