project:
  type: book

latex-auto-install: true

crossref:
  fig-prefix: figure     # (default is "Figure")
  tbl-prefix: tableau    # (default is "Table")

lang: fr
# language: _language.yml   # customized, "tableau" plutôt que "table", etc.

book:

  title: "Analyse et conception de logiciels"
  subtitle: "![nuage de mots](images/wordle_ordre_alph.png){width=70%}"
  cover-image: images/wordle_ordre_alph.png
  image: images/wordle_ordre_alph.png
  
  author: 
    - "Christopher Fuhrman"
    - "Yvan Ross"
  date: "2022-10-19"
  date-format: "DD MMMM YYYY"
  chapters:
    - index.qmd # Preface
    - AnalyseConception.qmd
    - Besoins.qmd
    - CasUtilisation.qmd
    - MDD.qmd
    - DSS.qmd
    - GRASP.qmd
    - DetteTechnique.qmd
    - Contrats.qmd
    - RDCU.qmd
    - TDD.qmd
    - Réusinage.qmd
    - TravailEquipe.qmd
    - Outils-UML.qmd
    - GRASP-GoF.qmd
    - Fiabilité.qmd
    - Diagrammes d'activités.qmd
    - Diagrammes d'états.qmd
    - ConceptionPackages.qmd
    - Diagrammes de déploiement.qmd
    - Laboratoires.qmd
    - references.qmd
  # repo-actions: [source, issue]

bibliography: references.bib
citations-hover: true
citation-location: document
link-citations: true # pandoc setting
# citeproc: true # causes quarto to hang
# latex-auto-install: true
latex-auto-mk: true
link-external-icon: true

format:

  epub: 
    epub-cover-image: "images/wordle_ordre_alph.png"

  html:
    header-includes: |
      <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
            rel="stylesheet" data-external="1"/>
    # https://quarto.org/docs/output-formats/html-themes.html#overview
    theme: simplex
    

  pdf:
    # has to be latexmk for .plantuml plugin to work (because it generates .svg files)
    pdf-engine: latexmk
    # template: partials/template.tex
    colorlinks: true
    documentclass: scrbook
    toc: true
    toc-depth: 2
    highlight-style: github
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    fontfamily: libertinus
    fontfamilyoptions: 
      - osf
      - p
    fontsize: 11pt
    header-includes: 
      - \usepackage{colortbl}
      - \usepackage[scaled=.8]{cascadia-code}
    # Bibliographies in French have raised r and e for the number "édition" e.g. 1re, 3e
      - \DeclareUnicodeCharacter{1D49}{$^\text{e}$}
      - \DeclareUnicodeCharacter{02B3}{$^\text{r}$}

# filters must be run in the proper order here
filters:
  - filters/fr-nbsp.lua
  - filters/diagram-generator.lua
  - quarto
  - filters/pandoc-quotes.lua

#
# Note: If JAVA_HOME, PLANTUML and DOT system variables are correctly set 
# (and the tools they point to are installed), 
# you should not need the following meta data variables
#

# javaPath: C:/Program Files/Java/jdk1.8.0_331/bin/java.exe
# plantumlPath: G:/My Drive/PlantUML/plantuml.jar
# dotPath: C:/Program Files/Graphviz/bin/dot.exe
