project:
  type: book
  language: _language.yml   # customized, "tableau" plutôt que "table", etc.

crossref:
  fig-prefix: figure     # (default is "Figure")
  tbl-prefix: tableau    # (default is "Table")

lang: fr

book:

  #cover-image: images/LOG210wordle_ordre_alph.png
  subtitle: "![nuage de mots](images/LOG210wordle_ordre_alph.png){width=70%}"
  title: "LOG210 Analyse et conception de logiciels"
  
  #subtitle: "Notes de cours"
  author: 
    - "Christopher Fuhrman"
    - "Yvan Ross"
  date: "2022-05-06"
  chapters:
    - index.qmd
    - AnalyseConception.qmd
    - Besoins.qmd
    - CasUtilisation.qmd
    - MDD.qmd
    - DSS.qmd
    - GRASP.qmd
    - DetteTechnique.qmd
    - Contrats.qmd
    - RDCU.qmd
    - TDD.qmd
    - Réusinage.qmd
    - TravailEquipe.qmd
    - Outils-UML.qmd
    - GRASP-GoF.qmd
    - Fiabilité.qmd
    - Diagrammes d'activités.qmd
    - Diagrammes d'états.qmd
    - ConceptionPackages.qmd
    - Diagrammes de déploiement.qmd
    - Laboratoires.qmd
    - references.qmd
  # repo-actions: [source, issue]

bibliography: references.bib
citations-hover: true
citation-location: document
citecolor: blue
# citeproc: true
# latex-auto-install: true
latex-auto-mk: true

format:

  epub: 
    epub-cover-image: "images/LOG210wordle_ordre_alph.png"

  html:
    header-includes: |
      <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
            rel="stylesheet" data-external="1"/>
    # include-in-header:
    #   - font-awesome.html
    # https://quarto.org/docs/output-formats/html-themes.html#overview
    # theme: cosmo
    # needed for inline plantuml/graphviz figures
    self-contained: true
    link-external-icon: true
    

  pdf:
    # has to be latexmk for .plantuml plugin to work (not sure why, see )
    pdf-engine: latexmk
    documentclass: scrbook
    lof: true
    lot: true
    toc: true
    toc-depth: 2
    highlight-style: github
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    fontfamily: libertinus
    fontfamilyoptions: 
      - osf
      - p
      - tt=false
    fontsize: 11pt
    # monofont: libertinus-mono
    # monofont: cm
    colorlinks: true
    header-includes: 
    # - \input{glyphtounicode}
    # - \pdfgentounicode=1
    # - \usepackage[style=french]{csquotes}
    # - \usepackage{fontawesome5}
    # - \usepackage{fontawesome}
    # - \usepackage{tcolorbox}
    - \usepackage{colortbl}
    # - \newtcolorbox{myquote}{colback=red!5!white, colframe=red!75!black}
    # - \renewenvironment{quote}{\begin{myquote}}{\end{myquote}}
    # Use courrier for monospace? https://tex.stackexchange.com/a/142319/17868
#    - \usepackage{inconsolata}
#    - \usepackage[scaled]{beramono}
    - \usepackage[scaled=.8]{cascadia-code}
    # Bibliographies in French have raised r and e for the number "édition" e.g. 1re, 3e
    - \DeclareUnicodeCharacter{1D49}{$^\text{e}$}
    - \DeclareUnicodeCharacter{02B3}{$^\text{r}$}
    # # Float control
    # - \usepackage{float}
    # - \floatplacement{figure}{htbp}
    # # Allow changing font size of code blocks, using \small right before the code fence, for example 
    # # https://stackoverflow.com/a/47492620/1168342
    # - \usepackage{setspace}
    # - \usepackage{hyperref}
    # - \usepackage[hyperpageref]{backref}

# filters must be run in the proper order here
filters:
  - filters/pandoc-quotes.lua
  - filters/diagram-generator.lua
  - quarto

#
# Note: If JAVA_HOME, PLANTUML and DOT system variables are correctly set 
# (and the tools they point to are installed), 
# you should not need the following meta data variables
#

# javaPath: C:/Program Files/Java/jdk1.8.0_331/bin/java.exe
# plantumlPath: G:/My Drive/PlantUML/plantuml.jar
# dotPath: C:/Program Files/Graphviz/bin/dot.exe

log-level: debug
