on: 
  push:
    branches: main
  pull_request:
    branches: main

  workflow_dispatch:

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2 
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        # with:
        #   # To install LaTeX to build PDF book 
        #   tinytex: true 
          # uncomment below and fill to pin a version
          # version: 0.9.600
      
      # add software dependencies here

      # Java for PlantUML
      - name: Get Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      
      - name: Check env for java
        run: echo "The JAVA_HOME is set to $JAVA_HOME"

      # PlantUML jar


      # Render
      - name: Render to HTML
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html


      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          # don't re-render
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
      